package com.laorencel.uilibrary.util.kt

object CrcUtil {
    private const val BITS_OF_BYTE = 8
    private const val POLYNOMIAL = 0xA001
    private const val INITIAL_VALUE = 0xFFFF
    private const val FF = 0xFF

    fun crc16(array: ByteArray): ByteArray {
        var res = INITIAL_VALUE
        for (data in array) {
            res = res xor (data.toInt() and FF)
            for (i in 0 until BITS_OF_BYTE) {
                res = if (res and 0x0001 == 1) res shr 1 xor POLYNOMIAL else res shr 1
            }
        }
        val lowByte: Byte = (res shr 8 and FF).toByte()
        val highByte: Byte = (res and FF).toByte()
        return array.plus(highByte).plus(lowByte)
    }

    fun crc16(array: IntArray): ByteArray {
        val byteArray = ByteArray(array.size + 2)
        var res = INITIAL_VALUE
        for (index in array.indices) {
            res = res xor array[index]
            byteArray[index] = array[index].toByte()
            for (i in 0 until BITS_OF_BYTE) {
                res = if (res and 0x0001 == 1) res shr 1 xor POLYNOMIAL else res shr 1
            }
        }
        val lowByte: Byte = (res shr 8 and FF).toByte()
        val highByte: Byte = (res and FF).toByte()
        byteArray[array.size] = highByte
        byteArray[array.size + 1] = lowByte
        return byteArray
    }

    fun crc16Verify(array: ByteArray): Boolean {
        if (array.size < 3) throw RuntimeException("数组长度不合法")
        var res = INITIAL_VALUE
        for (index in 0..array.size - 3) {
            res = res xor (array[index].toInt() and FF)
            for (i in 0 until BITS_OF_BYTE) {
                res = if (res and 0x0001 == 1) res shr 1 xor POLYNOMIAL else res shr 1
            }
        }
        val lowByte: Byte = (res shr 8 and FF).toByte()
        val highByte: Byte = (res and FF).toByte()
        return highByte == array[array.size - 2] && lowByte == array[array.size - 1]
    }


    /**
     * CRC8 校验 多项式x8+x2+x+1 简记式0x07
     *
     * @param bytes
     * @param off 起始位置
     * @param len 长度
     * @return
     */
    fun crc8_0x07(bytes: ByteArray, off: Int = 0, len: Int = bytes.size): Byte {
//        var result = 0xFF.toByte()
        var result = 0x00.toByte()
        for (i in 0 until len) {
            result = CRC8_0x07_TABLE[result.toInt() xor (bytes[i + off].toInt() and 0xFF) and 0xFF]
        }
        return (result.toLong() and 0xFFL).toByte()
    }

    /**
     * CRC8 校验 多项式x8+x5+x4+1 简记式0x31
     *
     * @param bytes 数据
     * @param offset 起始位置
     * @param len 长度
     * @param preValue 之前的校验值
     * @return 校验值
     */
    fun crc8_0x31(bytes: ByteArray, offset: Int = 0, len: Int = bytes.size, preValue: Byte = 0): Byte {
        var ret = preValue
        for (i in offset until (offset + len)) {
            ret = CRC8_0X31_TABLE[(0x00ff and (ret.toInt() xor bytes[i].toInt()))]
        }
        return ret
    }

    private val CRC8_0x07_TABLE: ByteArray = byteArrayOf(
        0x00.toByte(), 0x07.toByte(), 0x0e.toByte(), 0x09.toByte(), 0x1c.toByte(), 0x1b.toByte(),
        0x12.toByte(), 0x15.toByte(), 0x38.toByte(), 0x3f.toByte(), 0x36.toByte(), 0x31.toByte(),
        0x24.toByte(), 0x23.toByte(), 0x2a.toByte(), 0x2d.toByte(), 0x70.toByte(), 0x77.toByte(),
        0x7e.toByte(), 0x79.toByte(), 0x6c.toByte(), 0x6b.toByte(), 0x62.toByte(), 0x65.toByte(),
        0x48.toByte(), 0x4f.toByte(), 0x46.toByte(), 0x41.toByte(), 0x54.toByte(), 0x53.toByte(),
        0x5a.toByte(), 0x5d.toByte(), 0xe0.toByte(), 0xe7.toByte(), 0xee.toByte(), 0xe9.toByte(),
        0xfc.toByte(), 0xfb.toByte(), 0xf2.toByte(), 0xf5.toByte(), 0xd8.toByte(), 0xdf.toByte(),
        0xd6.toByte(), 0xd1.toByte(), 0xc4.toByte(), 0xc3.toByte(), 0xca.toByte(), 0xcd.toByte(),
        0x90.toByte(), 0x97.toByte(), 0x9e.toByte(), 0x99.toByte(), 0x8c.toByte(), 0x8b.toByte(),
        0x82.toByte(), 0x85.toByte(), 0xa8.toByte(), 0xaf.toByte(), 0xa6.toByte(), 0xa1.toByte(),
        0xb4.toByte(), 0xb3.toByte(), 0xba.toByte(), 0xbd.toByte(), 0xc7.toByte(), 0xc0.toByte(),
        0xc9.toByte(), 0xce.toByte(), 0xdb.toByte(), 0xdc.toByte(), 0xd5.toByte(), 0xd2.toByte(),
        0xff.toByte(), 0xf8.toByte(), 0xf1.toByte(), 0xf6.toByte(), 0xe3.toByte(), 0xe4.toByte(),
        0xed.toByte(), 0xea.toByte(), 0xb7.toByte(), 0xb0.toByte(), 0xb9.toByte(), 0xbe.toByte(),
        0xab.toByte(), 0xac.toByte(), 0xa5.toByte(), 0xa2.toByte(), 0x8f.toByte(), 0x88.toByte(),
        0x81.toByte(), 0x86.toByte(), 0x93.toByte(), 0x94.toByte(), 0x9d.toByte(), 0x9a.toByte(),
        0x27.toByte(), 0x20.toByte(), 0x29.toByte(), 0x2e.toByte(), 0x3b.toByte(), 0x3c.toByte(),
        0x35.toByte(), 0x32.toByte(), 0x1f.toByte(), 0x18.toByte(), 0x11.toByte(), 0x16.toByte(),
        0x03.toByte(), 0x04.toByte(), 0x0d.toByte(), 0x0a.toByte(), 0x57.toByte(), 0x50.toByte(),
        0x59.toByte(),
        0x5e.toByte(),
        0x4b.toByte(),
        0x4c.toByte(),
        0x45.toByte(),
        0x42.toByte(),
        0x6f.toByte(),
        0x68.toByte(),
        0x61.toByte(),
        0x66.toByte(),
        0x73.toByte(),
        0x74.toByte(),
        0x7d.toByte(),
        0x7a.toByte(),
        0x89.toByte(),
        0x8e.toByte(),
        0x87.toByte(),
        0x80.toByte(),
        0x95.toByte(),
        0x92.toByte(),
        0x9b.toByte(),
        0x9c.toByte(),
        0xb1.toByte(),
        0xb6.toByte(),
        0xbf.toByte(),
        0xb8.toByte(),
        0xad.toByte(),
        0xaa.toByte(),
        0xa3.toByte(),
        0xa4.toByte(),
        0xf9.toByte(),
        0xfe.toByte(),
        0xf7.toByte(),
        0xf0.toByte(),
        0xe5.toByte(),
        0xe2.toByte(),
        0xeb.toByte(),
        0xec.toByte(),
        0xc1.toByte(),
        0xc6.toByte(),
        0xcf.toByte(),
        0xc8.toByte(),
        0xdd.toByte(),
        0xda.toByte(),
        0xd3.toByte(),
        0xd4.toByte(),
        0x69.toByte(),
        0x6e.toByte(),
        0x67.toByte(),
        0x60.toByte(),
        0x75.toByte(),
        0x72.toByte(),
        0x7b.toByte(),
        0x7c.toByte(),
        0x51.toByte(),
        0x56.toByte(),
        0x5f.toByte(),
        0x58.toByte(),
        0x4d.toByte(),
        0x4a.toByte(),
        0x43.toByte(),
        0x44.toByte(),
        0x19.toByte(),
        0x1e.toByte(),
        0x17.toByte(),
        0x10.toByte(),
        0x05.toByte(),
        0x02.toByte(),
        0x0b.toByte(),
        0x0c.toByte(),
        0x21.toByte(),
        0x26.toByte(),
        0x2f.toByte(),
        0x28.toByte(),
        0x3d.toByte(),
        0x3a.toByte(),
        0x33.toByte(),
        0x34.toByte(),
        0x4e.toByte(),
        0x49.toByte(),
        0x40.toByte(),
        0x47.toByte(),
        0x52.toByte(),
        0x55.toByte(),
        0x5c.toByte(),
        0x5b.toByte(),
        0x76.toByte(),
        0x71.toByte(),
        0x78.toByte(),
        0x7f.toByte(),
        0x6a.toByte(),
        0x6d.toByte(),
        0x64.toByte(),
        0x63.toByte(),
        0x3e.toByte(),
        0x39.toByte(),
        0x30.toByte(),
        0x37.toByte(),
        0x22.toByte(),
        0x25.toByte(),
        0x2c.toByte(),
        0x2b.toByte(),
        0x06.toByte(),
        0x01.toByte(),
        0x08.toByte(),
        0x0f.toByte(),
        0x1a.toByte(),
        0x1d.toByte(),
        0x14.toByte(),
        0x13.toByte(),
        0xae.toByte(),
        0xa9.toByte(),
        0xa0.toByte(),
        0xa7.toByte(),
        0xb2.toByte(),
        0xb5.toByte(),
        0xbc.toByte(),
        0xbb.toByte(),
        0x96.toByte(),
        0x91.toByte(),
        0x98.toByte(),
        0x9f.toByte(),
        0x8a.toByte(),
        0x8d.toByte(),
        0x84.toByte(),
        0x83.toByte(),
        0xde.toByte(),
        0xd9.toByte(),
        0xd0.toByte(),
        0xd7.toByte(),
        0xc2.toByte(),
        0xc5.toByte(),
        0xcc.toByte(),
        0xcb.toByte(),
        0xe6.toByte(),
        0xe1.toByte(),
        0xe8.toByte(),
        0xef.toByte(),
        0xfa.toByte(),
        0xfd.toByte(),
        0xf4.toByte(),
        0xf3.toByte()
    )

    private var CRC8_0X31_TABLE: ByteArray = byteArrayOf(
        0.toByte(),
        94.toByte(),
        188.toByte(),
        226.toByte(),
        97.toByte(),
        63.toByte(),
        221.toByte(),
        131.toByte(),
        194.toByte(),
        156.toByte(),
        126.toByte(),
        32.toByte(),
        163.toByte(),
        253.toByte(),
        31.toByte(),
        65.toByte(),
        157.toByte(),
        195.toByte(),
        33.toByte(),
        127.toByte(),
        252.toByte(),
        162.toByte(),
        64.toByte(),
        30.toByte(),
        95.toByte(),
        1.toByte(),
        227.toByte(),
        189.toByte(),
        62.toByte(),
        96.toByte(),
        130.toByte(),
        220.toByte(),
        35.toByte(),
        125.toByte(),
        159.toByte(),
        193.toByte(),
        66.toByte(),
        28.toByte(),
        254.toByte(),
        160.toByte(),
        225.toByte(),
        191.toByte(),
        93.toByte(),
        3.toByte(),
        128.toByte(),
        222.toByte(),
        60.toByte(),
        98.toByte(),
        190.toByte(),
        224.toByte(),
        2.toByte(),
        92.toByte(),
        223.toByte(),
        129.toByte(),
        99.toByte(),
        61.toByte(),
        124.toByte(),
        34.toByte(),
        192.toByte(),
        158.toByte(),
        29.toByte(),
        67.toByte(),
        161.toByte(),
        255.toByte(),
        70.toByte(),
        24.toByte(),
        250.toByte(),
        164.toByte(),
        39.toByte(),
        121.toByte(),
        155.toByte(),
        197.toByte(),
        132.toByte(),
        218.toByte(),
        56.toByte(),
        102.toByte(),
        229.toByte(),
        187.toByte(),
        89.toByte(),
        7.toByte(),
        219.toByte(),
        133.toByte(),
        103.toByte(),
        57.toByte(),
        186.toByte(),
        228.toByte(),
        6.toByte(),
        88.toByte(),
        25.toByte(),
        71.toByte(),
        165.toByte(),
        251.toByte(),
        120.toByte(),
        38.toByte(),
        196.toByte(),
        154.toByte(),
        101.toByte(),
        59.toByte(),
        217.toByte(),
        135.toByte(),
        4.toByte(),
        90.toByte(),
        184.toByte(),
        230.toByte(),
        167.toByte(),
        249.toByte(),
        27.toByte(),
        69.toByte(),
        198.toByte(),
        152.toByte(),
        122.toByte(),
        36.toByte(),
        248.toByte(),
        166.toByte(),
        68.toByte(),
        26.toByte(),
        153.toByte(),
        199.toByte(),
        37.toByte(),
        123.toByte(),
        58.toByte(),
        100.toByte(),
        134.toByte(),
        216.toByte(),
        91.toByte(),
        5.toByte(),
        231.toByte(),
        185.toByte(),
        140.toByte(),
        210.toByte(),
        48.toByte(),
        110.toByte(),
        237.toByte(),
        179.toByte(),
        81.toByte(),
        15.toByte(),
        78.toByte(),
        16.toByte(),
        242.toByte(),
        172.toByte(),
        47.toByte(),
        113.toByte(),
        147.toByte(),
        205.toByte(),
        17.toByte(),
        79.toByte(),
        173.toByte(),
        243.toByte(),
        112.toByte(),
        46.toByte(),
        204.toByte(),
        146.toByte(),
        211.toByte(),
        141.toByte(),
        111.toByte(),
        49.toByte(),
        178.toByte(),
        236.toByte(),
        14.toByte(),
        80.toByte(),
        175.toByte(),
        241.toByte(),
        19.toByte(),
        77.toByte(),
        206.toByte(),
        144.toByte(),
        114.toByte(),
        44.toByte(),
        109.toByte(),
        51.toByte(),
        209.toByte(),
        143.toByte(),
        12.toByte(),
        82.toByte(),
        176.toByte(),
        238.toByte(),
        50.toByte(),
        108.toByte(),
        142.toByte(),
        208.toByte(),
        83.toByte(),
        13.toByte(),
        239.toByte(),
        177.toByte(),
        240.toByte(),
        174.toByte(),
        76.toByte(),
        18.toByte(),
        145.toByte(),
        207.toByte(),
        45.toByte(),
        115.toByte(),
        202.toByte(),
        148.toByte(),
        118.toByte(),
        40.toByte(),
        171.toByte(),
        245.toByte(),
        23.toByte(),
        73.toByte(),
        8.toByte(),
        86.toByte(),
        180.toByte(),
        234.toByte(),
        105.toByte(),
        55.toByte(),
        213.toByte(),
        139.toByte(),
        87.toByte(),
        9.toByte(),
        235.toByte(),
        181.toByte(),
        54.toByte(),
        104.toByte(),
        138.toByte(),
        212.toByte(),
        149.toByte(),
        203.toByte(),
        41.toByte(),
        119.toByte(),
        244.toByte(),
        170.toByte(),
        72.toByte(),
        22.toByte(),
        233.toByte(),
        183.toByte(),
        85.toByte(),
        11.toByte(),
        136.toByte(),
        214.toByte(),
        52.toByte(),
        106.toByte(),
        43.toByte(),
        117.toByte(),
        151.toByte(),
        201.toByte(),
        74.toByte(),
        20.toByte(),
        246.toByte(),
        168.toByte(),
        116.toByte(),
        42.toByte(),
        200.toByte(),
        150.toByte(),
        21.toByte(),
        75.toByte(),
        169.toByte(),
        247.toByte(),
        182.toByte(),
        232.toByte(),
        10.toByte(),
        84.toByte(),
        215.toByte(),
        137.toByte(),
        107.toByte(),
        53
    )
}